---
name: "Main"

"on":
  schedule:
    - cron: "0 */12 * * *"
  push: {}

permissions:
  actions: "write"
  contents: "write"
  issues: "write"
  pull-requests: "write"
  checks: "write"
  deployments: "write"

jobs:
  pre-commit-job:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Set up python and pip cache"
        uses: "actions/setup-python@v5.1.0"
        with:
          python-version: "3.11.4"
          cache: "pip"
      - name: "Install dependencies"
        run: "pip install -r requirements.txt"
      - name: "Set up pre-commit cache"
        uses: "actions/cache@v4.0.2"
        with:
          path: "~/.cache/pre-commit"
          key: "pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}"
      - name: "Run pre-commit"
        run: "pre-commit run --all-files --color=always --show-diff-on-failure"

  renovate-job:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Run Renovate"
        uses: "renovatebot/github-action@v40.1.12"
        with:
          renovate-version: "35.127.1"
          configurationFile: "./renovate-config.js"
          token: "${{ secrets.RENOVATE_TOKEN }}"

  release-job:
    needs: "pre-commit-job"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Run semantic-release"
        uses: "cycjimmy/semantic-release-action@v4.1.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
...
