---
name: "Renovate"

"on":
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}
  push: {}

permissions:
  actions: "write"
  contents: "write"
  issues: "write"
  pull-requests: "write"
  checks: "write"
  deployments: "write"

jobs:
  renovate-job:
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.2.2"
      - name: "Run Renovate"
        uses: "renovatebot/github-action@v41.0.14"
        with:
          renovate-version: "39.170.2"
          configurationFile: "./renovate-config.js"
          token: "${{ secrets.RENOVATE_TOKEN }}"
...
